# Generated by Django 5.0.8 on 2026-05-16 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_seed_demo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ['name']},
        ),
    ]
